micuintus/harbour-Berlin-Vegan

qml/harbour-berlin-vegan.qml
This change makes the app more portable to other platforms.
=> Use plain Qt to listen for application activity change

BerlinVegan.pro, src/BerlinVegan.cpp
The plan is to add V-Play support without breaking the current Sailfish
environment.
Ref #48
=> Prepare build system for V-Play

BerlinVegan.pro, ios/Project-Info.plist
We need to add an Info.plist for the iOS build and add
UIViewControllerBasedStatusBarAppearance.
=> Show status bar on iOS

qml/components/JsonDownloadHelper.qml
and switch it to a resource URI
in the fallback case.
// Github issue #4 and #48 and #40
=> Fix #60: JsonDownloadHelper

rpm/harbour-berlin-vegan.changes
about automatic JSON DB download from the internet.
=> Add forgotton changelog entry for the 0.9 release

ios/Project-Info.plist
Apple's Beta App Review process revealed, that we need proper sentences
and not just dummy strings here.
See:
* https://developer.apple.com/ios/human-interface-guidelines/ui-views/alerts/
=> Update NSLocation* strings

qml/components-Sailfish/ActionMenuItem.qml, qml/components-Sailfish/SectionHeader.qml, qml/harbour-berlin-vegan.qml, translations/harbour-berlin-vegan-en.ts, translations/harbour-berlin-vegan.ts
caused during #31 / #102.
SORRY!
=> [SailfishOS] Fix git rebase fckup

qml/pages/VenueDescription.qml
in expanded state (that it has te same distance
to the separator than the description below it).
// Github issue #105
=> Improve spacing of CollapsibleItem

qml/components-v-play/Theme.qml, qml/pages/VenueList.qml
(and the usage of them in the VenueList)
to better match the design as provided by our designer.
// See Github issue #105
=> [v-play] Adapt padding Theme definitions

qml/components-generic/VenueDescriptionHeader.qml, qml/pages/VenueDescription.qml
=> [Option 1] Put street & distance label in a non-opaque field

qml/Silica4v-play/DetailItem.qml, qml/Silica4v-play/Label.qml
in DetailItem.qml (key writing over values).
Although not really relevant for newer phones,
it might happen with older ones (iPhone 3 / 4).
=> [v-play] Take precautions against overwrites

qml/Silica4v-play/DetailItem.qml, qml/components-v-play/SectionHeader.qml, qml/components-v-play/Theme.qml
* Clean up DetailItem and SectionHeader construction
* Distance between SectionHeader and DetailItem was too large
* Font size of DetailItem was too large (Medium not Small)
=> Fix #129 and fix different font size in DetailItem

qml/components-generic/Database.js, qml/components-generic/IconToolBar.qml, qml/components-generic/qmldir, qml/components-generic/resources-components-generic.qrc, qml/harbour-berlin-vegan.qml
Do not talk to the SQLite database directly.
Sources:
* http://doc.qt.io/qt-5/qtquick-localstorage-localstorage-database-js.html
Closes #91
=> Extract favorite local storage code to own file

qml/components-Sailfish/Theme.qml, qml/components-v-play/Theme.qml, qml/pages/VenueList.qml, qml/pages/VenueMapPage.qml
This way a user can see once more the veg*an category of the restaurant.
Closes #154
=> Color the venue marker like in map overview

qml/components-Sailfish/Theme.qml, qml/components-v-play/Theme.qml
Orange and red are taken from the Berlin-Vegan web map:
* https://www.berlin-vegan.de/map/#/
=> Change marker color to our CI

qml/components-v-play/MenuItem.qml, qml/harbour-berlin-vegan.qml
in signal handlers of menu items and react to all
changes of the required properties.
V-Play somehow re-arragned how they set up their
pages and send out signals (selected() etc.).
=> Fix #178: Check for required properties to exist

qml/pages/VenueFilterSettings.qml
when clicking on it in selected state.
=> Fix #191: [SailfishOS] Don't disable radio button

src/VenueModel.cpp
=> Fix #195: Rm trailing whitespaces and newlines

rpm/BerlinVegan.yaml, rpm/harbour-berlin-vegan.changes
and BerlinVegan.yaml for upcoming 3.2 release.
=> [SailfishOS] Update harbour-berlin-vegan.changes

src/VenueModel.cpp
https://code.woboq.org/qt5/qtbase/src/corelib/tools/qstringalgorithms_p.h.html#_ZN17QStringAlgorithms17simplified_helperERT_
for fixing Github issue #195 instead of a self-implemented
solution.
=> Use Qt's built-in function QString::simplified()

src/OpeningHoursAlgorithms.h
=> Add International Women’s Day as holiday

qml/silica4felgo/TextSwitch.qml
=> Fix alignment of new AppSwitch
