micuintus/harbour-Berlin-Vegan

qml/harbour-berlin-vegan.qml
For some reason that I cannot explain the list sorting works only on
iOS, if this source code is removed.
Ref #48
=> [v-play] remove Component.onCompleted in PositionSource

qml/Sailfish/Silica/ApplicationWindow.qml, qml/Sailfish/Silica/Label.qml, qml/Sailfish/Silica/ListItem.qml, qml/Sailfish/Silica/Theme.qml, qml/Sailfish/Silica/qmldir
With this patch we show the content of the list delegate directly,
instead of accessing the IDs from inside the module. Therefore we set
the label component to be visible again, remove the texts from the
simple row and add our own Theme implementation.
Closes #56
=> Add theme implementation

qml/components-v-play/MenuItem.qml, qml/components-v-play/Theme.qml, qml/pages/VenueList.qml, qml/pages/VenueMapPage.qml
The pushAttached feature of the Sailfish pageStack
(which we use to put the map for one venue on the
right hand side of the VenueDescription page)
is not available on v-play.
A navigation paradigm like this (where the currently shown
page isn't the top of the navigation stack) is also very
uncommon on iOS and Android. We therefore extented the
pushAttached() interface by one parameter: An icon that
is shown on the right side of the navigation bar (where
you would have an 'arrow to the right' symbol if you
transferred the Sailfish style navigation scheme strictly),
which you can use to then actually call the attached-pushed
page.
In contrast to Sailfish, we do not actually push the page
when pushAttached() is being called. Instead the page is
only being pushed lazily once you hit the …
=> [v-play] Provide a pushAttached() implementation

qml/components-Sailfish/Map.qml, qml/components-v-play/Map.qml, qml/pages/VenueMapPage.qml
as it brings awesome OpenGL based rendering to the map.
Unfortunately, we cannot enable this for SailfishOS,
because they are on Qt < 5.9.
Closes #43
=> [v-play] Move v-play over to MapBoxGL

qml/components-v-play/IconButton.qml, qml/components-v-play/Theme.qml
With the V-Play 2.12.x update "IconType.mapmarker" is gone. Just let's
rely on the Material Icon font directly.
=> fix location marker

qml/components-v-play/IconButton.qml, qml/pages/VenueMapPage.qml
When zooming in and out one can see, that the map marker icon does not
point to the correct position all the time. This is because, there is an
invisible rectangle around the icon that needs to be taken into
account.
With this patch we center the icon horizontally and align it to the
bottom in the parent. Additionally we set the anchor point when zooming
to that exact point.
The 'anchors.fill: parent' also fixes the icons in the IconToolBar:
there weren't vertically centered, but only horizontally.
Closes #88
=> [v-play] fix map marker not pointing to correct position

qml/pages/about/AboutBerlinVegan.qml
B/C it doesn't make really sense to include
it again. Plus, the 'license file'
qrc:/imports/Sailfish/Silica/OpacityRampEffectBase.qml
isn't available on SailfishOS (at least not there),
=> [SailfishOS] Flter out jolla Silica credit

qml/pages/VenueDescription.qml
Some idiot broke this with 38538533a34b47aeb0f7ec017e564ae4883d50e0.
=> Fix broken truncation in VenueDescription

qml/pages/VenueMapOverviewPage.qml
Although we stack up the navigation with map views, without this patch a
user has to go back all the stack and select the venue from the list to
get directions in Apple Maps.
Closes #153
=> Show "get directions", when coming from map overview

qml/pages/VenueMapOverviewPage.qml
This way a user does not need to zoom out that much.
Closes #155
=> Reduce zoom level in map overview

qml/components-Sailfish/Theme.qml, qml/components-generic/PageIndicator.qml, qml/components-generic/SwipeView.qml, qml/components-generic/VenueDescriptionHeader.qml, qml/components-generic/qmldir, qml/components-generic/resources-components-generic.qrc, qml/components-v-play/Theme.qml
Often we have more than one image for a venue. To display them all we
use a SwipeView and a PageIndicator to show the user, that he/she can
swipe through the images.
Note: we cannot use upstream implementation, because SailfishOS does not
support Qt Quick Controls 2 at the moment.
Closes #1
=> Display all images in venue description

qml/components-Sailfish/MenuItem.qml, qml/components-v-play/ActionMenuItem.qml, qml/components-v-play/MenuItem.qml, qml/harbour-berlin-vegan.qml
Shortened explanation:
NavigationItem is derived from Tab
<https://v-play.net/doc/vplayapps-navigationitem/>
and Tabs are lazily loaded
(if the 'active' property isn't true on start).
FYI: Tabs are derived from Loader and the loading happens here:
<https://code.woboq.org/qt5/qtdeclarative/src/quick/items/qquickloader.cpp.html#597>.
Tabs being lazily loaded doesn't cause any problems per se,
but we did create the actual page to be shown in ActionMenuItem
(in our case, this page was VenueList.qml) immediately. Now this page
already existed, but not its surrounding navigation stack, etc.
Only when the surrounding menu item is being (by clicking on it),
all the signal connections are being set up correctly.
=> Fix #143 --- without breaking #141 again

qml/pages/VenueMapOverviewPage.qml
on Sailfish for Map Overview. Somehow the values
seem to differ on SailfishOS and V-Play / Mapbox.
=> Fix #166: Go back to original zoom level

.gitmodules, BerlinVegan.pro, qml/components-Sailfish/Theme.qml, qml/components-generic/IconToolBar.qml, qml/components-generic/VenueDescriptionAlgorithms.js, qml/components-v-play/Theme.qml, qml/harbour-berlin-vegan.qml, qml/pages/VenueFilterSettings.qml, qml/pages/VenueList.qml, src/BerlinVegan.cpp, src/VenueModel.cpp
As nice at it is, with our own C++ model in place,
we don't need Cutehacks' gel anymore. Now that
Sailfish's Qt is finally at least on 5.6,
we can remove gel completely, as we can use QJSValueIterator
on Sailfish, as well.
=> Remove last traces of Cutehacks::gel

qml/components-generic/VenueDescriptionHeader.qml
Due to the error below, the if condition can not be evaluated and
therefore model is not set to '1'.
Error:
* VenueDescriptionHeader.qml:57: TypeError: Cannot read property
'length' of undefined
=> Fix: placeholder image sometime not shown

qml/pages/VenueMapOverviewPage.qml
When coming from VenueMapOverviewPage location marker's color is always
red, instead of green for e.g. vegan venues.
We forgot to forward the information (in VenueList.qml, we are doing it
correctly already).
Closes #183
=> [v-play] Fix location marker's color

qml/pages/VenueMapOverviewPage.qml
It could result in a different venue if the sorting has changed in the
meantime.
TODO: Refactor restaurant handover in way that it isn't longer based on
those colum indices.
=> Fix #185 Don't reevaluate currRestaurant onClicked

qml/pages/VenueMapPage.qml
The idea is, at least for now, to open the external map app when
clicking anywhere in venue description's map view. This does not work,
especially when clicking on the venue's location marker, which is very
bad UX.
Closes #209
=> Open external map when clicking on markers

qml/Silica4v-play/Text.qml, qml/Silica4v-play/qmldir, qml/Silica4v-play/resources-Silica4v-play.qrc
V-Play 2.15.1 ships Qt 5.10.1, which changed the default font family on
iOS changed from ".SF UI Text" to "System Font Regular" for unknown
reasons, which looks really bad.
See:
* https://github.com/micuintus/harbour-Berlin-Vegan/issues/207
Closes #207
=> [ios] Fix broken font after V-Play 2.15.1 update

qml/pages/VenueMapPage.qml
With this patch a user can choose if he/she wants to open the
destination either with Apple or with Google Maps.
If an app is not installed it will open the link in the browser.
On desktop one does not get a chooser presented. This behaviour is
implemented in NativeUtils.
Note: Currently the strings are hard-coded, because I don't see the
necessity for translating those strings for our supported languages.
=> [ios] Add possibility to choose map app

.travis.yml
for being able to use the Qt version that comes with the
build environment (instead of having to install the sbinner version).
=> [CI] Switch travis build to Ubuntu Xenial

qml/components-felgo/Theme.qml, qml/components-sailfish/Theme.qml
Currently venues that are labeled vegan are shown red, although they
should be orange.
// github issue #300
Closes #306
=> Fix leftover of e0c0a15

qml/components-felgo/NavigationStackWithPushAttached.qml, src/BerlinVegan.cpp
Afterwards to also get correct HDPI maps on Android.
=> Fix #286: Enable HDPI scaling & repair navbar size
